# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
       AppBandle\Entity\User: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
            main:
                anonymous: ~
                form_login:
                    login_path: login
                    check_path: login

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
