# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # ...

    providers:
        our_db_provider:
            entity:
               class: AppBundle:User
               property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        main:
          anonymous: ~
          pattern: ^/admin
          simple_form:
                authenticator: AppBundle\Security\PasswordAuthenticator
                login_path: login
                check_path: login_check